# Setup
# Change this later
title:               'Jai Gandhi'
tagline:             ''
description:         'Just a chill guy'
url:                 http://jaigandhi.com
baseurl:             ''
paginate:            5
paginate_path:       '/socialclub/page:num'
permalink:           pretty

# About/contact
author:
  name:              Jai Gandhi
  url:               https://www.instagram.com/_jaigandhi/
  email:             jaimgandhi@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
