# Setup
# Production configuration
title:               'Jai Gandhi'
tagline:             ''
description:         'Jai Gandhi'
url:                 https://jaigandhi.life
baseurl:             ''  # Production baseurl (empty for root domain)
paginate:            5
paginate_path:       '/socialclub/page:num'
permalink:           pretty

# About/contact
author:
  name:              Jai Gandhi
  url:               https://www.instagram.com/_jaigandhi/
  email:             jaimgandhi@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
